### PR TITLE
Unmunge LD_LIBRARY_PATH by Xilinx tools which conflicts with awk.

### PR DESCRIPTION
**Pull request by DaveMcEwan**
Explicitly clear for just the use of awk to find git version.
https://www.xilinx.com/support/answers/66998.html

### CODE REVIEW

**Comment by Jbalkind** [comment]
Could you say a bit more about the circumstances that necessitate this? I don't think we've seen issues on the systems we use. Is it a Vivado version thing?

**Comment by DaveMcEwan** [comment]
Yes I think it's a Vivado version thing where settings64.sh munges LD_LIBRARY_PATH to something incompatible with awk which results in a rather unhelpful error.
So the fix is simply to unset LD_LIBRARY_PATH only for the calls to awk.

Same problem reported on several forums with different projects:
http://www.googoolia.com/wp/2015/04/21/awk-symbol-lookup-error-awk-undefined-symbol-mpfr_z_sub/
https://github.com/pavel-demin/red-pitaya-notes/issues/426
https://bluehatsoft.blogspot.com/2015/09/awk-symbol-lookup-error-awk-undefined.html
...

**Comment by Jbalkind** [comment]
Ok I'll merge and hopefully at some point they just sort it out so it becomes unnecessary. I'd be a bit surprised if issues arose with calling awk without LD_LIBRARY_PATH set, given its simplicity.

**Comment by Jbalkind** [comment]
And thanks!

**Pull request merged**
