### PR TITLE
Update goldfinger et. al to ANSI C and improve portability to 64-bit

### PR DESCRIPTION
**Pull request by jrrk**
It is rather offputting to have the first experience with openpiton being a whole load of warning messages, and a lack of portability to 64-bit. Therefore I have attempted to solve all but one of these in this patch. This exposed a few incorrect casts, but nothing I think that would affect functionality

### CODE REVIEW

**Comment by Jbalkind** [comment]
This is wonderful!

Before I get into the nitty gritty, could you remove the Makefile.system you included? It's a symbolic link which was updated to your local path (I think) on running mktools

**Comment by Jbalkind** [comment]
WOW I really never lived until I ran `mktools` with no warnings (I've run this tool so many times and just always hated the 2+ full screens of warnings)

Only issue I see remaining is in GCC 7.3.1 - if we're in the process of fixing, could I ask you to do a little more? I'm getting the following and it looks like an easy fix

```
g++ -c -g -I./ -DDEBUG=1 -D__unix__ -DDATE='"Fri Nov 30 09:40:05 EST 2018"' TreSearch.C
TreSearch.C: In member function 'void TreSearch::MoveAndSetEndPtr()':
TreSearch.C:68:19: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
     if (endPtr == '\0') {
                   ^~~~
make: *** [Makefile:59: TreSearch.o] Error 1
```

Actually that's amazing looking at the code. I think it's a decade-old bug...

**Comment by jrrk** [comment]
I guess my environment (Ubuntu-16.04) is a little different to yours, which is why I do not see that bug.

**Comment by Jbalkind** [comment]
Yeah I wanted to try with the newest GCC I could in case it pointed out anything like that.

I'm (very) happy with this, thanks a ton for taking the time! I'm going to merge to openpiton-dev first.

**Pull request merged**
