### PR TITLE
Remove inferred latches, fixes to enable VCS for Ariane, add new PLIC and bump Ariane version.

### PR DESCRIPTION
**Pull request by msfschaffner**
This implements the solution discussed in  #14 to remove the latches in `dynamic_node` and its variants.

### CODE REVIEW

**Comment by Jbalkind** [comment]
Are the storage_addr_trans(_unified).v changes something we could use the devices.xml for or is there some board-specific define that's also needed? Should/could they be aligned using any of the DDR parameter macros rather than hard-coding constants? I don't really understand this part of the patch.

**Comment by msfschaffner** [comment]
Yes, it's possible to use the information from `mc_defines.h` and from `devices.xml` and remove the board defines. That would however mean that we need to pass it through PyHP, and since you generate that file with another Python script (pitonunimap), I didn't change that yet. But I'm more than happy to use a generation approach without the board defines if that works for you...

**Comment by Jbalkind** [comment]
Synthesis for `dynamic_node` passes (no new warnings/errors, timing is met) so we should be good. Area is pretty different. Output of the area report is below. Also posting this in issue #14 

New design:

```Number of ports:                          693
Number of nets:                          5948
Number of cells:                         5515
Number of combinational cells:           4290
Number of sequential cells:              1194
Number of macros/black boxes:               0
Number of buf/inv:                        752
Number of references:                     448

Combinational area:               4897.736976
Buf/Inv area:                      662.103002
Noncombinational area:            5134.077067
Macro/Black Box area:                0.000000
Net Interconnect area:      undefined  (No wire load specified)

Total cell area:                 10031.814043
Total area:                 undefined

Core Area:                     16101
Aspect Ratio:                 1.0002
Utilization Ratio:            0.6231
```

Old design:

```
Number of ports:                          693
Number of nets:                          5902
Number of cells:                         5469
Number of combinational cells:           3920
Number of sequential cells:              1519
Number of macros/black boxes:               0
Number of buf/inv:                        754
Number of references:                     294

Combinational area:               3624.075009
Buf/Inv area:                      351.819004
Noncombinational area:            5501.808086
Macro/Black Box area:                0.000000
Net Interconnect area:      undefined  (No wire load specified)

Total cell area:                  9125.883094
Total area:                 undefined

Core Area:                     15354
Aspect Ratio:                 1.0046
Utilization Ratio:            0.5943```

**Comment by msfschaffner** [comment]
Could you resynthesize with [this](https://github.com/msfschaffner/openpiton/commit/3e3fd603976f0988064e1a7cbb3444e8448040cf) patch applied on top?

**Comment by Jbalkind** [comment]
Present things for VCS (if we're including them in this PR):
- line 2626 in sims,2.0: should add ariane here so that NO_MRA_VAL and NO_SLAM_RANDOM are set
- perf_counters in ariane should be ifdef'd out for VCS (or fixed to work in VCS)
- instruction tracer should be ifdef'd out for VCS
- Flist.ariane also needs +incdir+src/util
- sims,2.0 needs to set timescale for ariane somewhere - I've been setting it to 1ps/1ps using -vcs_build_args=-timescale=1ps/1ps but we should do it inside and only under ariane on vcs

**Comment by msfschaffner** [comment]
Ok, done. VCS works now.

The FPU is now enabled by default, but we still have to run all regressions and do some synthesis trials before we merge this one in.

**Comment by Jbalkind** [comment]
Basically happy to merge. The only two things I notice at this point:
- Is `PITON_CLK_GATE_USE_BUFG` used now? Seems it was added to the defines but then I think you killed the BUFGs
- Should we be concerned that rrarbiter and a couple of the others are under deprecated in common_cells?

**Comment by msfschaffner** [comment]
`PITON_CLK_GATE_USE_BUFG` is not needed anymore, I removed it from the sources.

Concerning the deprecated common cells: these cells have been superseded by newer and better implementations and will gradually be phased out. They are still available in the git repo though.

**Comment by Jbalkind** [comment]
Passes ETH CI - merging!

**Pull request merged**
