### PR TITLE
This adds preliminary support for the vcu118 FPGA board

### PR DESCRIPTION
**Pull request by msfschaffner**

### CODE REVIEW

**Comment by Jbalkind** [comment]
@leon575777642 could you take a look at the changes to the SD in this branch? In particular:

- the changes to the constraints in a few of the commits
- the use of a lower frequency clock on the vcu118 in 97dc7c4
- the changes to the SD interface in 7054dea

Michael said that with some of the updates, they're having trouble with some SD cards on the Genesys2.

**Comment by angl-dev** [comment]
Hi Michael,

I'm not an expert in constraints files, and the constraints file we've been using was from trial and error. I believe you're defining the constraints in a better way. However, my experience in SD card debugging suggests that either many SD cards do not strictly follow the specs, or the FPGA boards have extra delay or clock skew. No matter how, based on what I used to see on the oscilloscope, it's usually better to relax the constraint on the SD card side.

Specifically, I see that you're setting the minimum output delay to a negative value. I'm not sure but wouldn't that violate the hold time for the SD card?

**Comment by msfschaffner** [comment]
Hey @leon575777642,

Thanks for looking through the patch.

Yeah the SD cards tend to behave quite differently... I tested the newest Genesys2 build with three different SD cards (a new Kingston card, and a new and a very old SanDisk card), and for some of those the interface did not work anymore. Further, it did not work for any of the cards when I was testing on the VCU118 board with this PMOD0 to SD adapter: 

https://store.digilentinc.com/pmod-sd-full-sized-sd-card-slot/ 

Hence I changed the way data is output in the SD card controller:

1) I placed all regs (both I and O) into the IOB for minimal skew
2) I added registers to all outgoing signals in order to launch them on the falling clock edge to avoid hold timing issues
3) I formulated the constraints such that both input_delay and output_delay use the clock forwarded to the SD card as a reference

This seems to solve the problems on all FPGA builds that I tested with (VC707, G2, VCU118).

But I agree that the output_delay -min constraints should not be negative (it does not really matter in this case since the delays are with respect to the falling clock edge). I will change that and just set them to 0.0.

**Comment by Jbalkind** [comment]
@RTKarbon Could you take a look at the uart_mux.v latch change in de1b57e and the patches more generally to see if you can see why issues would've been introduced for pitonstream?

**Comment by alexeylavrov** [comment]
@msfschaffner  Thanks for removing latches in uart_mux.v. I should have put default values to all signals. However, this change should not affect stream testing in general. 
I did not see anything suspicious for mc, and devices. The only thing I noticed is that you align address by 32-bytes here: https://github.com/PrincetonUniversity/openpiton/blob/2adf33f755338a8e6631e44dd2a270ca15262362/piton/design/chipset/rtl/storage_addr_trans_unified.v#L46
while physical width is 64-byte aligned for whole burst:
https://github.com/PrincetonUniversity/openpiton/blob/2adf33f755338a8e6631e44dd2a270ca15262362/piton/design/chipset/include/mc_define.h#L57
@Jbalkind I was also thinking about bug which we found recently in packet_filter, but since Michael is using only one contiguous memory section from **64'h80000000** to **64'h100000000** it would not occur.
@msfschaffner  Can you describe which issues you have with **pitonstream** after porting to VCU118?

**Comment by msfschaffner** [comment]
Thanks for giving it a look, @RTKarbon. Ok I'll align that properly to 64bit boundaries.

The issue I have with pitonstream is not tied to a specific board... it's rather that it becomes very flaky and unstable on all boards when I build with the latch patches. I.e., if I run pitonstream 10 times, it would maybe succeed once, fail twice and in all other cases there would be no output at all and I have to reset.

I can send you a bitfile for G2 if you want to try yourself...

**Comment by alexeylavrov** [comment]
@msfschaffner That behavior is strange. The first idea from the top of my head is that it could be timing, but it is hard to imagine it would be the case for all boards. Which boards do you have beyond G2 and VCU118?
Could you also try to narrow down the problem by applying minimum set of changes to a base configuration? For example, can you take a working version from the main branch and apply part of patch only to UART latches and see it it causes pitonstream to fail on G2?

**Comment by msfschaffner** [comment]
Yeah I also thought that this should be something else than just a timing issue... We also have VC707 here. I plan to do a bisect of the latch patch as soon as I have some time...

**Comment by alexeylavrov** [comment]
Sounds good. Keep me updated. I will try your image next week. Also, could you point to the commit that image was built from?

**Comment by alexeylavrov** [comment]
@msfschaffner @Jbalkind 
I tested a bitfile Jon shared with me for Genesys2 and I did not see any issues with pitonstream. hello_world.c passed 128 out of 128 times

**Comment by msfschaffner** [comment]
Hi @RTKarbon, that's good to hear. @Jbalkind from which commit has this bitfile been generated?

**Comment by Jbalkind** [comment]
I think that you'd have to tell me - you sent me it a couple of weeks ago saying it was flaky

**Comment by msfschaffner** [comment]
Ahh ok I thought you generated your own bitfile in the meantime, sorry. I fear that the commit of that bitfile is out of date now since in the meantime we stabilized the latch-patch (and I rebased the vcu118 branch on top of that). I'll build a new one and give it a go.

**Pull request merged**
