### PR TITLE
update setup.tcl for newer vivado versions

### PR DESCRIPTION
**Pull request by tianrui-wei**
update setup.tcl to prevent python version conflicts for Vivado version > 2019.1
See this AR for detail https://www.xilinx.com/support/answers/72570.html
address issue #50

### CODE REVIEW

**Comment by Jbalkind** [comment]
Did this work for you in practice?

**Comment by claford-v-lawrence** [comment]
Yes. This is tested on Ubuntu 18.04 with both python2 and python 3 installed. Vivaldi version is 2019.2.

**Comment by tianrui-wei** [comment]
Yes, this is tested on Ubuntu 18.04 with both python2 and python3 installed. Vivado version is 2019.2.

**Comment by Jbalkind** [comment]
Ok excellent. Thanks for this one!

**Comment by tianrui-wei** [comment]
No problem!

**Pull request merged**
